export const PROBLEM_BOJ_COLLECT = 'PROBLEM_BOJ_COLLECT';
export const PROBLEM_BOJ_PROCESS = 'PROBLEM_BOJ_PROCESS';
export const PROBLEM_BOJ_LOAD = 'PROBLEM_BOJ_LOAD';

export const JOB_HANDLER_MAP = {
  [PROBLEM_BOJ_COLLECT]: PROBLEM_BOJ_COLLECT,
  [PROBLEM_BOJ_PROCESS]: PROBLEM_BOJ_PROCESS,
  [PROBLEM_BOJ_LOAD]: PROBLEM_BOJ_LOAD,
} as const;

export const JOB_STATE_PENDING = 'PENDING';
export const JOB_STATE_RUNNING = 'RUNNING';
export const JOB_STATE_COMPLETED = 'COMPLETED';
export const JOB_STATE_FAILED = 'FAILED';

export const JOB_STATE_MAP = {
  [JOB_STATE_PENDING]: 'PENDING',
  [JOB_STATE_RUNNING]: 'RUNNING',
  [JOB_STATE_COMPLETED]: 'COMPLETED',
  [JOB_STATE_FAILED]: 'FAILED',
} as const;
