export const PROBLEM_BOJ = 'PROBLEM_BOJ';
export const TODAY_PROBLEM_BOJ = 'TODAY_PROBLEM_BOJ';
export const PROBLEM_BOJ_USER = 'PROBLEM_BOJ_USER';

export const BATCH_PLAN_MAP = {
  [PROBLEM_BOJ]: PROBLEM_BOJ,
  [TODAY_PROBLEM_BOJ]: TODAY_PROBLEM_BOJ,
  [PROBLEM_BOJ_USER]: PROBLEM_BOJ_USER,
} as const;
