export const PROBLEM_BOJ_COLLECT = 'PROBLEM_BOJ_COLLECT';
export const PROBLEM_BOJ_PROCESS = 'PROBLEM_BOJ_PROCESS';
export const PROBLEM_BOJ_LOAD = 'PROBLEM_BOJ_LOAD';

export const JOB_KEY = {
  [PROBLEM_BOJ_COLLECT]: 'PROBLEM_BOJ_COLLECT',
  [PROBLEM_BOJ_PROCESS]: 'PROBLEM_BOJ_PROCESS',
  [PROBLEM_BOJ_LOAD]: 'PROBLEM_BOJ_LOAD',
};
